# Generated by Django 3.0.1 on 2022-03-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santaHood', '0002_product_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/santaHood/img/'),
        ),
    ]
