# Generated by Django 3.0.1 on 2022-03-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santaHood', '0006_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='coming soon...'),
        ),
    ]
