# Generated by Django 3.0.1 on 2022-03-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santaHood', '0009_auto_20220301_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='santaHood/static/santaHood/img/'),
        ),
    ]
